module.exports = {
	//Single-Teaser-Article
	NW_PER_SINGLE_TEASER_ARTICLE: "https://personal.natwest.com/personal/loans/home-improvement-loans.html",
	NW_PER_SINGLE_TEASER_ARTICLE_MOB: "https://personal.natwest.com/personal/loans/home-improvement-loans.m.html",
	RBS_PER_SINGLE_TEASER_ARTICLE: "https://personal.rbs.co.uk/personal/loans/home-improvement-loans.html",
	RBS_PER_SINGLE_TEASER_ARTICLE_MOB: "https://personal.rbs.co.uk/personal/loans/home-improvement-loans.m.html",
	ULSTER_PER_SINGLE_TEASER_ARTICLE: "https://digital.ulsterbank.co.uk/personal/help-and-support.html",
	ULSTER_PER_SINGLE_TEASER_ARTICLE_MOB: "https://digital.ulsterbank.co.uk/personal/help-and-support.m.html",
	ULSTER_ROI_PER_SINGLE_TEASER_ARTICLE: "https://digital.ulsterbank.ie/personal/security-centre.html",
	ULSTER_ROI_PER_SINGLE_TEASER_ARTICLE_MOB: "https://digital.ulsterbank.ie/personal/security-centre.m.html",
	LOMBARD_SINGLE_TEASER_ARTICLE: 'https://www.lombard.co.uk/lombard/support-centre.html',
	LOMBARD_SINGLE_TEASER_ARTICLE_MOB: 'https://www.lombard.co.uk/lombard/support-centre.m.html',
	LOMBARD_IE_SINGLE_TEASER_ARTICLE: 'https://lombard.ie/',
	LOMBARD_IE_SINGLE_TEASER_ARTICLE_MOB: 'https://lombard.ie/lombard-ireland.m.html',
	RBS_IF_SINGLE_TEASER_ARTICLE: 'https://www.rbsif.co.uk/',
	RBS_IF_SINGLE_TEASER_ARTICLE_MOB: 'https://www.rbsif.co.uk/invoice-finance.m.html',
	NW_BUS_SINGLE_TEASER_ARTICLE: "https://www.business.natwest.com/business/trade-hub/accounts-and-payments/global-liquidity.html",
	NW_BUS_SINGLE_TEASER_ARTICLE_MOB: "https://www.business.natwest.com/business/trade-hub/accounts-and-payments/global-liquidity.m.html",
	RBS_BUS_SINGLE_TEASER_ARTICLE: "https://www.business.rbs.co.uk/business/trade-hub/accounts-and-payments/global-liquidity.html",
	RBS_BUS_SINGLE_TEASER_ARTICLE_MOB: "https://www.business.rbs.co.uk/business/trade-hub/accounts-and-payments/global-liquidity.m.html",
	NW_INTERMEDIARY_SINGLE_TEASER_ARTICLE: 'http://www.intermediary.natwest.com/',
	NW_INTERMEDIARY_SINGLE_TEASER_ARTICLE_MOB: 'http://www.intermediary.natwest.com/intermediary-solutions.m.html',

	//WSC Accordion-Shelf
	//NW_PER_WSC_ACCORDION: 'https://personal.natwest.com/personal/support-centre.html',
	NW_BUS_WSC_ACCORDION: 'https://www.business.natwest.com/business/ways-to-bank.html',
	NW_BUS_WSC_ACCORDION_MOB: 'https://www.business.natwest.com/business/ways-to-bank.m.html',
	NW_PER_WSC_ACCORDION: 'https://personal.natwest.com/personal/support-centre/how-to-complain.html',
	NW_PER_WSC_ACCORDION_MOB: 'https://personal.natwest.com/personal/support-centre/how-to-complain.m.html',
	RBS_PER_WSC_ACCORDION: 'https://personal.rbs.co.uk/personal/ways-to-bank/mobile-app.html',
	RBS_PER_WSC_ACCORDION_MOB: 'https://personal.rbs.co.uk/personal/ways-to-bank/mobile-app.m.html',
	RBS_BUS_WSC_ACCORDION: 'https://www.business.rbs.co.uk/business/rbs-business-bankingsupportcentre/contact-us.html',
	RBS_BUS_WSC_ACCORDION_MOB: 'https://www.business.rbs.co.uk/business/rbs-business-bankingsupportcentre/contact-us.m.html',
	LOMBARD_WSC_ACCORDION: 'https://www.lombard.co.uk/lombard/contact-us.html',
	LOMBARD_WSC_ACCORDION_MOB: 'https://www.lombard.co.uk/lombard/contact-us.m.html',
	LOMBARD_IE_WSC_ACCORDION: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland.html',
	LOMBARD_IE_WSC_ACCORDION_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland.m.html',
	NW_MAR_WSC_ACCORDION: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/regulation.html',
	NW_MAR_WSC_ACCORDION_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/regulation.m.html',
	RBS_COM_WSC_ACCORDION: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/regulation.html',
	RBS_COM_WSC_ACCORDION_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/regulation.m.html',
	NW_INTER_WSC_ACCORDION: 'http://www.intermediary.natwest.com/intermediary-solutions.html',
	NW_INTER_WSC_ACCORDION_MOB: 'http://www.intermediary.natwest.com/intermediary-solutions.m.html',
	RBS_REMEMBERS_WSC_ACCORDION: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/regulation.html',
	RBS_REMEMBERS_WSC_ACCORDION_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/regulation.m.html',
	ULSTER_WSC_ACCORDION: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/regulation.html',
	ULSTER_WSC_ACCORDION_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/regulation.m.html',
	ULSTERIE_WSC_ACCORDION: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/regulation.html',
	ULSTERIE_WSC_ACCORDION_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/regulation.m.html',

	//WSC Accordion-composite
	NW_BUS_WSC_ACC_COMP: 'https://www.business.natwest.com/business/Review-of-interest-rates.html',
	NW_BUS_WSC_ACC_COMP_MOB: 'https://www.business.natwest.com/business/Review-of-interest-rates.m.html',
	NW_PER_WSC_ACCORDION_COMP: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/mortgages/switch-mortgage-deal1/after-2004.html',
	NW_PER_WSC_ACCORDION_COMP_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test-accordion.m.html',
	NW_MAR_WSC_ACCORDION_COMP: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test-accordion.html',
	NW_MAR_WSC_ACCORDION_COMP_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test-accordion.m.html',
	LOMBARD_ACCORDION_COMP: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/terms-and-conditions.html',
	LOMBARD_ACCORDION_COMP_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/terms-and-conditions.m.html',
	RBS_PER_WSC_ACCORDION_COMP: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/test-accordion.html',
	RBS_PER_WSC_ACCORDION_COMP_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/test-accordion.m.html',
	RBS_BUS_WSC_ACCORDION_COMP: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/test-accordion.html',
	RBS_BUS_WSC_ACCORDION_COMP_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/test-accordion.m.html',
	RBS_COM_WSC_ACCORDION_COMP: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test-accordion.html',
	RBS_COM_WSC_ACCORDION_COMP_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test-accordion.m.html',
	RBS_REM_WSC_ACCORDION_COMP: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test-accordion.html',
	RBS_REM_WSC_ACCORDION_COMP_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test-accordion.m.html',
	RBS_IF_WSC_ACCORDION_COMP: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test-accordion.html',
	RBS_IF_WSC_ACCORDION_COMP_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test-accordion.m.html',
	LOMBARD_WSC_ACC_COMP: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test-accordion.html',
	LOMBARD_WSC_ACC_COMP_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test-accordion.m.html',
	LOMBARD_IE_WSC_ACC_COMP: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test-accordion.html',
	LOMBARD_IE_WSC_ACC_COMP_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test-accordion.m.html',
	ULSTERIE_WSC_ACC_COMP: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test-accordion.html',
	ULSTERIE_WSC_ACC_COMP_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test-accordion.m.html',
	ULSTER_WSC_ACC_COMP: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test-accordion.html',
	ULSTER_WSC_ACC_COMP_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test-accordion.m.html',

	//Benefit-List
	NW_PER_BENEFIT_LIST:"https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/technology.html",
	NW_PER_BENEFIT_LIST_MOB:"https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/technology.m.html",
	NW_BUS_BENEFIT_LIST: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/technology.html",
	NW_BUS_BENEFIT_LIST_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/technology.m.html",
	NW_MAR_BENEFIT_LIST: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/technology.html",
	NW_MAR_BENEFIT_LIST_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/technology.m.html",
	
	RBS_PER_BENEFIT_LIST: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/technology.html",
	RBS_PER_BENEFIT_LIST_MOB: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/technology.m.html",
	RBS_BUS_BENEFIT_LIST: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/technology.html",
	RBS_BUS_BENEFIT_LIST_MOB: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/technology.m.html",
	RBS_COM_BENEFIT_LIST: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/technology.html",
	RBS_COM_BENEFIT_LIST_MOB: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/technology.m.html",
	RBS_REM_BENEFIT_LIST: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/technology.html",
	RBS_REM_BENEFIT_LIST_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/technology.m.html",
	RBS_IF_BENEFIT_LIST: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/technology.html",
	RBS_IF_BENEFIT_LIST_MOB: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/technology.m.html",
	
	ULSTER_BENEFIT_LIST: "https://digital.ulsterbank.co.uk/personal/current-accounts/current-account.html",
	ULSTER_BENEFIT_LIST_MOB: "https://digital.ulsterbank.co.uk/personal/current-accounts/current-account.m.html",
	ULSTERBANK_IE: "https://digital.ulsterbank.ie/personal/current-accounts/student-account.html",
	ULSTERBANK_IE_MOB: "https://digital.ulsterbank.ie/personal/current-accounts/student-account.m.html",
	LOMBARD_UK: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/technology.html",				 
	LOMBARD_UK_MOB: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/technology.m.html",
	LOMBARD_UK_IE: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/technology.html",
	LOMBARD_UK_IE_MOB: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/technology.m.html",

	//Download-Shelf
	NW_PER_DOWNLOAD_SHELF: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_download.html",
	NW_PER_DOWNLOAD_SHELF_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_download.m.html",
	NW_MARK_DOWNLOAD_SHELF: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_download.html",
	NW_MARK_DOWNLOAD_SHELF_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_download.m.html",
	NW_BUS_DOWNLOAD_SHELF: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_download.html",
	NW_BUS_DOWNLOAD_SHELF_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_download.m.html",
	RBC_PER_DOWNLOAD_SHELF: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/test_download.html',
	RBC_PER_DOWNLOAD_SHELF_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/test_download.m.html',
	RBC_BUS_DOWNLOAD_SHELF: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_download.html',
	RBC_BUS_DOWNLOAD_SHELF_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_download.m.html',
	RBC_COM_DOWNLOAD_SHELF: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_download.html',
	RBC_COM_DOWNLOAD_SHELF_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_download.m.html',
	RBC_IF_DOWNLOAD_SHELF: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_download.html',
	RBC_IF_DOWNLOAD_SHELF_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_download.m.html',
	LOM_DOWNLOAD_SHELF: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_download.html',
	LOM_DOWNLOAD_SHELF_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_download.m.html',


	RBC_REM_DOWNLOAD_SHELF: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_download.html',
	RBC_REM_DOWNLOAD_SHELF_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_download.m.html',

	ULSTER_DOWNLOAD_SHELF: "https://ulsterbankie-nfte1.arete.managedtest.com/roi/personal/wsctest/test_download.html",
	ULSTER_DOWNLOAD_SHELF_MOB: "https://ulsterbankie-nfte1.arete.managedtest.com/roi/personal/wsctest/test_download.m.html",
	
	//Header
	NW_PER_HEADER: 'https://personal.natwest.com/',
	NW_PER_HEADER_MOB: 'https://personal.natwest.com/personal.m.html',
	RBS_PER_HEADER: 'https://personal.rbs.co.uk/',
	RBS_PER_HEADER_MOB: 'https://personal.rbs.co.uk/personal.m.html',
	ULSTER_HEADER: 'https://digital.ulsterbank.co.uk/',
	ULSTER_HEADER_MOB: 'https://digital.ulsterbank.co.uk/personal.m.html',
	ULSTER_ROI_HEADER: 'https://digital.ulsterbank.ie/',
	ULSTER_ROI_HEADER_MOB: 'https://digital.ulsterbank.ie/personal.m.html',
	NW_BUS_HEADER: 'https://www.business.natwest.com/',
	NW_BUS_HEADER_MOB: 'https://www.business.natwest.com/business.m.html',
	RBS_BUS_HEADER: 'https://www.business.rbs.co.uk/',
	RBS_BUS_HEADER_MOB: 'https://www.business.rbs.co.uk/business.m.html',
	RBS_COM_HEADER: 'https://www.rbs.com/',
	RBS_COM_HEADER_MOB: 'https://www.rbs.com/rbs.m.html',
	RBS_IF_HEADER: 'https://www.rbsif.co.uk/',
	RBS_IF_HEADER_MOB: 'https://www.rbsif.co.uk/invoice-finance.m.html',
	LOMBARD_HEADER: 'https://www.lombard.co.uk/',
	LOMBARD_HEADER_MOB: 'https://www.lombard.co.uk/lombard.m.html',
	NW_MARKETS_HEADER: 'https://www.natwestmarkets.com/',
	NW_MARKETS_HEADER_MOB: 'https://www.natwestmarkets.com/natwest-markets.m.html',
	NW_INTERMEDIARY_HEADER: 'http://www.intermediary.natwest.com/',
	NW_INTERMEDIARY_HEADER_MOB: 'http://www.intermediary.natwest.com/intermediary-solutions.m.html',
	RBS_REMEMBERS_HEADER: 'https://www.rbsremembers.com/',
	RBS_REMEMBERS_HEADER_MOB: 'https://www.rbsremembers.com/remembers.m.html',

	//Multiple Teaser Article Shelf
	NW_PER_MULTIPLE_TEASER_ARTICLE: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/testmultipleteaser.html',
	NW_PER_MULTIPLE_TEASER_ARTICLE_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/testmultipleteaser.m.html',
	RBS_PER_MULTIPLE_TEASER_ARTICLE: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/testmultipleteaser.html',
	RBS_PER_MULTIPLE_TEASER_ARTICLE_MOB: 'https://personal.rbs.co.uk/personal/life-moments/travel/travel-money.m.html',
	NW_BUS_MULTIPLE_TEASER_ARTICLE: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/testmultipleteaser.html',
	NW_BUS_MULTIPLE_TEASER_ARTICLE_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/testmultipleteaser.m.html',
	NW_MARKETS_TEASER_ARTICLE: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/testmultipleteaser.html',
	RBS_BUS_MULTIPLE_TEASER_ARTICLE: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/testmultipleteaser.html',
	RBS_BUS_MULTIPLE_TEASER_ARTICLE_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/testmultipleteaser.m.html',
	ULSTER_NI_MULTIPLE_TEASER_ARTICLE: 'https://digital.ulsterbank.co.uk/personal/help-and-support/open-banking.html',
	ULSTER_NI_MULTIPLE_TEASER_ARTICLE_MOB: 'https://digital.ulsterbank.co.uk/personal/help-and-support/open-banking.m.html',
	ULSTER_ROI_MULTIPLE_TEASER_ARTICLE: 'https://digital.ulsterbank.ie/personal/current-accounts/switch-to-ulster-bank.html',
	ULSTER_ROI_MULTIPLE_TEASER_ARTICLE_MOB: 'https://digital.ulsterbank.ie/personal/current-accounts/switch-to-ulster-bank.m.html',
	RBS_IF_MULTIPLE_TEASER_ARTICLE: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/testmultipleteaser.html',
	RBS_IF_MULTIPLE_TEASER_ARTICLE_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/testmultipleteaser.m.html',
	LOMBARD_MULTIPLE_TEASER_ARTICLE: 'https://www.lombard.co.uk/lombard/products-services/assets/construction-materials-handling-machinery.html',
	LOMBARD_MULTIPLE_TEASER_ARTICLE_MOB: 'https://www.lombard.co.uk/lombard/products-services/assets/construction-materials-handling-machinery.m.html',
	NW_INTERMEDIARY_MULTIPLE_TEASER_ARTICLE: 'http://www.intermediary.natwest.com/intermediary-solutions/placing-business.html',
	NW_INTERMEDIARY_MULTIPLE_TEASER_ARTICLE_MOB: 'http://www.intermediary.natwest.com/intermediary-solutions/placing-business.m.html',
	RBS_COM_MULTIPLE_TEASER_ARTICLE: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/testmultipleteaser.html',
	RBS_COM_MULTIPLE_TEASER_ARTICLE_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/testmultipleteaser.m.html',
	RBS_REM_MULTIPLE_TEASER_ARTICLE: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/testmultipleteaser.html',
	RBS_REM_MULTIPLE_TEASER_ARTICLE_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/testmultipleteaser.m.html',
	LOM_UK_MULTIPLE_TEASER_ARTICLE: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/testmultipleteaser.html',
	LOM_UK_MULTIPLE_TEASER_ARTICLE_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/testmultipleteaser.m.html',
	LOM_IE_MULTIPLE_TEASER_ARTICLE: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/testmultipleteaser.html',
	LOM_IE_MULTIPLE_TEASER_ARTICLE_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/testmultipleteaser.m.html',
	ULSTER_ROI_TEASER_MULTIPLE: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/testmultipleteaser.html',
	ULSTER_ROI_TEASER_MULTIPLE_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/testmultipleteaser.m.html',
	ULSTER_NI_MULTIPLE_TEASER_ARTICLE: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/testmultipleteaser.html',
	ULSTER_NI_MULTIPLE_TEASER_ARTICLE_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/testmultipleteaser.m.html',



	//Hero Carousel Shelf
	NW_PER_HERO_CAROUSEL: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/test_herocarousel.html',
	//NW_PER_HERO_CAROUSEL: 'https://personal.natwest.com/personal/life-moments.html',
	RBS_PER_HERO_CAROUSEL: 'https://personal.rbs.co.uk/personal/life-moments.html',
	NW_BUS_HERO_CAROUSEL: 'https://personalnatwestcom-sit2.arete.managedtest.com/business/life-moments.html',
	RBS_BUS_HERO_CAROUSEL: 'https://personalrbscouk-sit2.arete.managedtest.com/business/life-moments.html',
	NW_MARKETS_HERO_CAROUSEL: 'https://natwestmarketscom-sit2.arete.managedtest.com/natwest-markets/life-moments.html',
	RBS_COM_HERO_CAROUSEL: 'https://rbscom-sit2.arete.managedtest.com/rbs/life-moments.html',
	ULSTER_ROI_HERO_CAROUSEL: 'https://ulsterbankie-sit2.arete.managedtest.com/personal/life-moments.html',
	ULSTER_NI_HERO_CAROUSEL: 'https://ulsterbankcouk-sit2.arete.managedtest.com/personal/life-moments.html',
	RBS_IF_HERO_CAROUSEL: 'https://rbsifcouk-sit2.arete.managedtest.com/invoice-finance/life-moments.html',
	NW_INTERMEDIARY_HERO_CAROUSEL: 'https://personalnatwestcom-sit2.arete.managedtest.com/intermediary-solutions/life-moments.html',
	RBS_REMEMBERS_HERO_CAROUSEL: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/life-moments.html',

	//PDP Hero Shelf
	NW_PER_HERO_PDP: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/pdp-heroshelf.html?sdfsdf',
	NW_PER_HERO_PDP_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/pdp-heroshelf.m.html?sdfsdf',
	RBS_PER_HERO_PDP: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/pdp-heroshelf.html?sdfsdf',
	RBS_PER_HERO_PDP_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/pdp-heroshelf.m.html?sdfsdf',
	ULSTER_NI_HERO_PDP: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/pdp-heroshelf.html',
	ULSTER_NI_HERO_PDP_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/pdp-heroshelf.m.html',
	ULSTER_ROI_HERO_PDP: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/pdp-heroshelf.html',
	ULSTER_ROI_HERO_PDP_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/pdp-heroshelf.m.html',
	NW_MARKETS_HERO_PDP: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/pdp-heroshelf.html',
	NW_MARKETS_HERO_PDP_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/pdp-heroshelf.m.html',
	RBS_IF_HERO_PDP: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/pdp-heroshelf.html',
	RBS_IF_HERO_PDP_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/pdp-heroshelf.m.html',
	NW_BUS_HERO_PDP: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/pdp-heroshelf.html',
	NW_BUS_HERO_PDP_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/pdp-heroshelf.m.html',
	RBS_BUS_HERO_PDP: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/pdp-heroshelf.html',
	RBS_BUS_HERO_PDP_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/pdp-heroshelf.m.html',

	//Carousel Shelf
	NW_PER_CAROUSEL: 'https://personal.natwest.com/personal.html',
	NW_BUS_CAROUSEL: 'https://www.business.natwest.com/business.html',
	RBS_BUS_CAROUSEL: 'https://www.business.rbs.co.uk/business.html',
	RBS_PER_CAROUSEL: 'https://personal.rbs.co.uk/personal.html',
	LOM_UK_CAROUSEL: 'https://www.lombard.co.uk/',
	LOM_IE_CAROUSEL: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/WSC/personal.html',
	NW_INTERMEDIARY_CAROUSEL: 'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/carousel.html',
	ULSTER_NI_CAROUSEL: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/carousel.html',
	ULSTER_ROI_CAROUSEL: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/carousel.html',
	NW_MARKETS_CAROUSEL: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/carousel.html',
	RBSCOM_CAROUSEL: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/carousel.html',
	RBSREMEMBERSCOM_CAROUSEL: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/carousel.html',


	NW_BUS_CAROUSEL_MOB: 'https://www.business.natwest.com/business.m.html',
	NW_PER_CAROUSEL_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal.m.html?',
	RBS_BUS_CAROUSEL_MOB: 'https://www.business.rbs.co.uk/business.m.html',
	RBS_PER_CAROUSEL_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal.m.html',
	LOM_UK_CAROUSEL_MOB: 'https://www.lombard.co.uk/lombard.m.html',
	LOM_IE_CAROUSEL_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/WSC/personal.m.html',
	NW_INTERMEDIARY_CAROUSEL_MOB: 'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/carousel.m.html',
	ULSTER_NI_CAROUSEL_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/carousel.m.html',
	ULSTER_ROI_CAROUSEL_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/carousel.m.html',
	NW_MARKETS_CAROUSEL_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/carousel.m.html',
	RBSCOM_CAROUSEL_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/carousel.m.html',
	RBSREMEMBERSCOM_CAROUSEL_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/carousel.m.html',


	//FAQ
	NW_PER_FAQ: 'https://personal.natwest.com/personal/credit-cards/manage/lost-stolen.html',
	NW_PER_FAQ_MOB: 'https://personal.natwest.com/personal/credit-cards/manage/lost-stolen.m.html',
	NW_PER_FAQ_TOOL: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/mortgage-overpayment-tool.html',
	NW_PER_MOB_FAQ_TOOL: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/mortgage-overpayment-tool.m.html',
	NW_BUS_FAQ: 'https://www.business.natwest.com/business/natwest-business-bankingsupportcentre.html',
	NW_BUS_FAQ_MOB: 'https://www.business.natwest.com/business/natwest-business-bankingsupportcentre.m.html',
	NW_MARKETS_FAQ: 'https://natwestmarketscom-sit2.arete.managedtest.com/natwest-markets/manage.html',
	NW_MARKETS_FAQ_MOB: 'https://natwestmarketscom-sit2.arete.managedtest.com/natwest-markets/manage.m.html',
	RBS_PER_FAQ: 'https://personal.rbs.co.uk/personal/myrewards.html',
	RBS_PER_FAQ_TEST: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/test_faq.html',
	RBS_PER_FAQ_MOB: 'https://personal.rbs.co.uk/personal/myrewards.m.html',
	RBS_BUS_FAQ: 'https://www.business.rbs.co.uk/business/manage.html',
	RBS_BUS_FAQ_MOB: 'https://www.business.rbs.co.uk/business/manage.m.html',
	ULSTER_NI_FAQ: 'https://digital.ulsterbank.co.uk/personal/current-accounts/manage-your-current-account.html',
	ULSTER_NI_FAQ_MOB: 'https://digital.ulsterbank.co.uk/personal/current-accounts/manage-your-current-account.m.html',
	ULSTER_ROI_FAQ: 'https://digital.ulsterbank.ie/personal/current-accounts/manage-your-current-account.html',
	ULSTER_ROI_FAQ_MOB: 'https://digital.ulsterbank.ie/personal/current-accounts/manage-your-current-account.m.html',
	RBS_REMEMBERS_FAQ: "https://rbsrememberscom-sit2.arete.managedtest.com/remembers/faqtest.html",
	RBS_REMEMBERS_FAQ_MOB: "https://rbsrememberscom-sit2.arete.managedtest.com/remembers/faqtest.m.html",
	RBS_IF_FAQ: 'https://rbsifcouk-sit2.arete.managedtest.com/invoice-finance/manage-your-credit-card.html',
	RBS_IF_FAQ_MOB: 'https://rbsifcouk-sit2.arete.managedtest.com/invoice-finance/manage-your-credit-card.m.html',
	RBS_COM_FAQ: "https://rbscom-sit2.arete.managedtest.com/rbs/faqtest.html",
	RBS_COM_FAQ_MOB: "https://rbscom-sit2.arete.managedtest.com/rbs/faqtest.m.html",
	LOMBARD_UK_FAQ: "https://lombardcouk-sit2.arete.managedtest.com/lombard/about-lombard.html",
	LOMBARD_UK_FAQ_MOB: "https://lombardcouk-sit2.arete.managedtest.com/lombard/about-lombard.m.html",
	//NATWEST intermiatry not allowing the template
	//Dynamic Clock
	NW_PER_DYNAMIC_CLOCK: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/dynamic_clock.html',
	NW_PER_DYNAMIC_CLOCK_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/dynamic_clock.m.html',
	RBS_PER_DYNAMIC_CLOCK: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/dynamic_clock.html',
	RBS_PER_DYNAMIC_CLOCK_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/dynamic_clock.m.html',
	ULSTER_DYNAMIC_CLOCK: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/dynamic_clock.html',
	ULSTER_DYNAMIC_CLOCK_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/dynamic_clock.m.html',
	ULSTER_ROI_DYNAMIC_CLOCK: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/dynamic_clock.html',
	ULSTER_ROI_DYNAMIC_CLOCK_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/dynamic_clock.m.html',
	NW_BUS_DYNAMIC_CLOCK: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/dynamic_clock.html',
	NW_BUS_DYNAMIC_CLOCK_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/dynamic_clock.m.html',
	RBS_BUS_DYNAMIC_CLOCK: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/dynamic_clock.html',
	RBS_BUS_DYNAMIC_CLOCK_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/dynamic_clock.m.html',
	RBS_COM_DYNAMIC_CLOCK: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/dynamic_clock.html',
	RBS_COM_DYNAMIC_CLOCK_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/dynamic_clock.m.html',
	RBS_IF_DYNAMIC_CLOCK: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/dynamic_clock.html',
	RBS_IF_DYNAMIC_CLOCK_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/dynamic_clock.m.html',
	LOMBARD_DYNAMIC_CLOCK: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/dynamic_clock.html',
	LOMBARD_DYNAMIC_CLOCK_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/dynamic_clock.m.html',
	LOMBARD_IE_DYNAMIC_CLOCK: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/dynamic_clock.html',
	LOMBARD_IE_DYNAMIC_CLOCK_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/dynamic_clock.m.html',
	NW_MARKETS_DYNAMIC_CLOCK: 'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/dynamic_clock.html',
	NW_MARKETS_DYNAMIC_CLOCK_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/dynamic_clock.m.html',
	NW_INTERMEDIARY_DYNAMIC_CLOCK: 'https://personalnatwestcom-sit2.arete.managedtest.com/intermediary-solutions/dynamicClock.html',
	NW_INTERMEDIARY_DYNAMIC_CLOCK_MOB: 'https://personalnatwestcom-sit2.arete.managedtest.com/intermediary-solutions/dynamicClock.m.html',
	RBS_REMEMBERS_DYNAMIC_CLOCK: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/dynamic_clock.html',
	RBS_REMEMBERS_DYNAMIC_CLOCK_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/dynamic_clock.m.html',

	//Next Step
	NW_PER_NEXT_STEP: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_nextstep.html',
	NW_PER_NEXT_STEP_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_nextstep.m.html',
	RBS_PER_NEXT_STEP: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_nextstep.html',
	RBS_PER_NEXT_STEP_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_nextstep.m.html',
	RBS_COM_NEXT_STEP: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_nextstep.html",
	RBS_COM_NEXT_STEP_MOB: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_nextstep.m.html",
	LOMBARD_NEXT_STEP: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test_nextstep.html',
	LOMBARD_NEXT_STEP_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test_nextstep.m.html',
	LOMBARD_IE_NEXT_STEP: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_nextstep.html',
	LOMBARD_IE_NEXT_STEP_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_nextstep.m.html',
	ULSTER_NI_NEXT_STEP: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test_nextstep.html',
	ULSTER_NI_NEXT_STEP_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test_nextstep.m.html',
	ULSTER_ROI_NEXT_STEP: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test_nextstep.html',
	ULSTER_ROI_NEXT_STEP_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test_nextstep.m.html',
	RBS_IF_NEXT_STEP: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_nextstep.html',
	RBS_IF_NEXT_STEP_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_nextstep.m.html',
	NW_BUS_NEXT_STEP: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_nextstep.html',
	NW_BUS_NEXT_STEP_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_nextstep.m.html',
	NW_MAR_NEXT_STEP: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_nextstep.html",
	NW_MAR_NEXT_STEP_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_nextstep.m.html",
	RBS_BUS_NEXT_STEP: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_nextstep.html",
	RBS_BUS_NEXT_STEP_MOB: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_nextstep.m.html",
	RBS_REM_NEXT_STEP: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_nextstep.html",
	RBS_REM_NEXT_STEP_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_nextstep.m.html",

	//Contact-details shelf
	NW_PER_CONTACT_DETAILS: 'https://personal.natwest.com/personal/ways-to-bank/post-office.html',
	NW_PER_CONTACT_DETAILS_MOB: 'https://personal.natwest.com/personal/ways-to-bank/post-office.m.html',
	RBS_PER_CONTACT_DETAILS: 'https://personal.rbs.co.uk/personal/ways-to-bank/post-office.html',
	RBS_PER_CONTACT_DETAILS_MOB: 'https://personal.rbs.co.uk/personal/ways-to-bank/post-office.m.html',
	LOMBARD_CONTACT_DETAILS: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/ContactDetailsTest.html',
	LOMBARD_CONTACT_DETAILS_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/ContactDetailsTest.html',
	RBS_COM_CONTACT_DETAILS: 'https://rbscom-nfte1.arete.managedtest.com/heritage/ContactDetailsTest.html',
	RBS_COM_CONTACT_DETAILS_MOB: 'https://rbscom-nfte1.arete.managedtest.com/heritage/ContactDetailsTest.m.html',
	NW_MARKETS_CONTACT_DETAILS: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/ContactDetailsTest.html',
	NW_MARKETS_CONTACT_DETAILS_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/ContactDetailsTest.m.html',
	LOMBARD_IE_CONTACT_DETAILS: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/ContactDetailsTest.html',
	LOMBARD_IE_CONTACT_DETAILS_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/ContactDetailsTest.m.html',
	RBS_IF_CONTACT_DETAILS: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/ContactDetailsTest.html',
	RBS_IF_CONTACT_DETAILS_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/ContactDetailsTest.m.html',
	RBS_REMEMBERS_CD: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/ContactDetailsTest.html',
	RBS_REMEMBERS_CD_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/ContactDetailsTest.m.html',
	ULSTER_NI_CONTACT_DETAILS: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/ContactDetailsTest.html',
	ULSTER_NI_CONTACT_DETAILS_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/ContactDetailsTest.m.html',
	ULSTER_ROI_CONTACT_DETAILS: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/ContactDetailsTest.html',
	ULSTER_ROI_CONTACT_DETAILS_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/ContactDetailsTest.m.html',
	NW_BUS_CONTACT_DETAILS: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/ContactDetailsTest.html',
	NW_BUS_CONTACT_DETAILS_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/ContactDetailsTest.m.html',
	RBS_BUS_CONTACT_DETAILS: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/ContactDetailsTest.html',
	RBS_BUS_CONTACT_DETAILS_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/ContactDetailsTest.m.html',
	NW_INTERMEDIARY_CD: 'http://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/ContactDetailsTest.html',
	NW_INTERMEDIARY_CD_MOB: 'http://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/ContactDetailsTest.m.html',

	//Currency Converter
	NW_PER_CURRENCY_CONVERTER: 'https://personal.natwest.com/personal/life-moments/travel/spending-abroad/costs-of-using-your-card-abroad/holiday-spending-calculator.html',
	NW_PER_CURRENCY_CONVERTER_MOB: 'https://personal.natwest.com/personal/life-moments/travel/spending-abroad/costs-of-using-your-card-abroad/holiday-spending-calculator.m.html',
	RBS_PER_CURRENCY_CONVERTER: 'https://personal.rbs.co.uk/personal/life-moments/travel/travel-money.html',
	RBS_PER_CURRENCY_CONVERTER_MOB: 'https://personal.rbs.co.uk/personal/life-moments/travel/travel-money.m.html',




	//Email Content
	NW_PER_EMAIL_CONTENT:'https://personal.natwest.com/tool/emailtool/softlogon.html',

	//Reward Calculator
	NW_PER_REWARD_CALCULATOR:'https://personal.natwest.com/personal/current-accounts/compare-current-accounts/reward-account/reward-calculator.html',
	NW_PER_REWARD_CALCULATOR_MOBILE:'https://personal.natwest.com/personal/current-accounts/compare-current-accounts/reward-account/reward-calculator.m.html',
	RBS_PER_REWARD_CALCULATOR:'https://personal.rbs.co.uk/personal/current-accounts/compare-current-accounts/reward-account/reward-calculator.html',
	RBS_PER_REWARD_CALCULATOR_MOBILE:'https://personal.rbs.co.uk/personal/current-accounts/compare-current-accounts/reward-account/reward-calculator.m.html',


	//Subnav shelf
	NW_PER_SUBNAV: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_subnav.html',
	NW_PER_SUBNAV_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_subnav.m.html',
	LOMBARD_SUBNAV: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_subnav.html',
	LOMBARD_SUBNAV_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_subnav.m.html',
	NW_BUS_SUBNAV: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_subnav.html",
	NW_BUS_SUBNAV_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_subnav.m.html",
	NW_MAR_SUBNAV: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_subnav.html",
	NW_MAR_SUBNAV_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_subnav.m.html",
	NW_INTER_SUBNAV: "http://intermediarynatwestcom-sit2.arete.managedtest.com/intermediary-solutions/subnavtest.html",
	NW_INTER_SUBNAV_MOB: "http://intermediarynatwestcom-sit2.arete.managedtest.com/intermediary-solutions/subnavtest.m.html",
	RBS_BUS_SUBNAV: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_subnav.html",
	RBS_BUS_SUBNAV_MOB: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_subnav.m.html",
	RBS_COM_SUBNAV: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_subnav.html",
	RBS_COM_SUBNAV_MOB: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_subnav.m.html",
	RBS_IF_SUBNAV: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_subnav.html",
	RBS_IF_SUBNAV_MOB: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_subnav.m.html",
	ULSTER_NI_SUBNAV: "https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test_subnav.html",
	ULSTER_NI_SUBNAV_MOB: "https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test_subnav.m.html",
	ULSTER_ROI_SUBNAV: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test_subnav.html",
	ULSTER_ROI_SUBNAV_MOB: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test_subnav.m.html",
	RBS_REMEMBERS_SUBNAV: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_subnav.html",
	RBS_REMEMBERS_SUBNAV_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_subnav.m.html",
	//NW_PER_SUBNAV:	'https://personal.natwest.com/personal/savings/compare-savings-accounts-new.html',
	NW_PER_SUBNAV: 'https://personalnatwestcom-sit2.arete.managedtest.com/personal/subnavTestPage.html',
	NW_PER_SUBNAV_MOB: 'https://personalnatwestcom-sit2.arete.managedtest.com/personal/subnavTestPage.m.html',
	RBS_PER_SUBNAV: 'https://personalrbscouk-sit2.arete.managedtest.com/personal/subnvTestPage.html',
	RBS_PER_SUBNAV_MOB: 'https://personalrbscouk-sit2.arete.managedtest.com/personal/subnvTestPage.m.html',
	LOMBARD_SUBNAV: 'https://www.lombard.co.uk/lombard/support-centre.html',
	LOMBARD_SUBNAV_MOB: 'https://www.lombard.co.uk/lombard/support-centre.m.html',
	//LOMBARD_SUBNAV:  'https://lombardcouk-sit2.arete.managedtest.com/lombard/SubnavTestPage.html',
	//LOMBARD_SUBNAV_MOB:  'https://lombardcouk-sit2.arete.managedtest.com/lombard/SubnavTestPage.m.html',
	//NW_BUS_SUBNAV:"https://www.business.natwest.com/business/natwest-business-bankingsupportcentre.html",
	//NW_BUS_SUBNAV_MOB:"https://www.business.natwest.com/business/natwest-business-bankingsupportcentre.m.html"
	NW_BUS_SUBNAV: "https://businessnatwestcom-sit2.arete.managedtest.com/business/subnavTestPage0.html",
	NW_BUS_SUBNAV_MOB: "https://businessnatwestcom-sit2.arete.managedtest.com/business/subnavTestPage0.m.html",
	NW_MAR_SUBNAV: "https://natwestmarketscom-sit2.arete.managedtest.com/natwest-markets/subnavtest.html",
	NW_MAR_SUBNAV_MOB: "https://natwestmarketscom-sit2.arete.managedtest.com/natwest-markets/subnavtest.m.html",
	NW_INTER_SUBNAV: "http://intermediarynatwestcom-sit2.arete.managedtest.com/intermediary-solutions/subnavtest.html",
	NW_INTER_SUBNAV_MOB: "http://intermediarynatwestcom-sit2.arete.managedtest.com/intermediary-solutions/subnavtest.m.html",
	RBS_BUS_SUBNAV: "https://businessrbscouk-sit2.arete.managedtest.com/business/subnvTestPage.html",
	RBS_BUS_SUBNAV_MOB: "https://businessrbscouk-sit2.arete.managedtest.com/business/subnvTestPage.m.html",
	RBS_IF_SUBNAV: "https://rbsifcouk-sit2.arete.managedtest.com/invoice-finance/subnavTest.html",
	RBS_IF_SUBNAV_MOB: "https://rbsifcouk-sit2.arete.managedtest.com/invoice-finance/subnavTest.m.html",
	ULSTER_NI_SUBNAV: "https://ulsterbankcouk-sit2.arete.managedtest.com/personal/subnavtest.html",
	ULSTER_NI_SUBNAV_MOB: "https://ulsterbankcouk-sit2.arete.managedtest.com/personal/subnavtest.m.html",
	ULSTER_ROI_SUBNAV: "https://ulsterbankie-sit2.arete.managedtest.com/personal/subnvtest.html",
	ULSTER_ROI_SUBNAV_MOB: "https://ulsterbankie-sit2.arete.managedtest.com/personal/subnvtest.m.html",

	//largefull
	RBS_COM_FULLWIDTHCAROUSEL: 'https://rbscom-dev2.arete.managedtest.com/rbs/dcoe-test/largefullwidthcarousel.html',


	//doweknowyouenhanced 
	NW_PER_DO_WE_KNOW_YOU_ENHANCED: 'https://personal.natwest.com/personal/savings/savings-builder/savings-builder-apply.html',
	NW_PER_DO_WE_KNOW_YOU_ENHANCED_MOB: 'https://personal.natwest.com/personal/savings/savings-builder/savings-builder-apply.m.html',
	RBS_PER_DO_WE_KNOW_YOU_ENHANCED: 'https://personal.rbs.co.uk/personal/loans/shared-content-area/apply-now-important-information.html',
	RBS_PER_DO_WE_KNOW_YOU_ENHANCED_MOB: 'https://personal.rbs.co.uk/personal/loans/shared-content-area/apply-now-important-information.m.html',
	ULSTER_ROI_DO_WE_KNOW_YOU_ENHANCED: 'https://digital.ulsterbank.ie/personal/current-accounts/non-roi-eu-residents.html',
	ULSTER_ROI_DO_WE_KNOW_YOU_ENHANCED_MOB: 'https://digital.ulsterbank.ie/personal/current-accounts/non-roi-eu-residents.m.html',
	ULSTER_NI_DO_WE_KNOW_YOU_ENHANCED: 'https://digital.ulsterbank.co.uk/personal/personal-loans/apply-now-hero.html',
	ULSTER_NI_DO_WE_KNOW_YOU_ENHANCED_MOB: 'https://digital.ulsterbank.co.uk/personal/personal-loans/apply-now-hero.m.html',
	LOMBARD_DO_WE_KNOW_YOU_ENHANCED: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/savings-builder-apply-test.html',
	LOMBARD_DO_WE_KNOW_YOU_ENHANCED_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/savings-builder-apply-test.m.html',
	NW_PER_DO_WE_KNOW_YOU_ENHANCED: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/savings-builder-apply.html',
	//frb investment

	NW_PER_FRB_INVESTMENT: 'https://personal.natwest.com/personal/savings/fixed-term-savingsaccount/fixed-term-saver-account-apply.html',
	NW_PER_FRB_INVESTMENT_MOB: 'https://personal.natwest.com/personal/savings/fixed-term-savingsaccount/fixed-term-saver-account-apply.m.html',
	NW_BUS_FRB_INVESTMENT: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/fixed-term-saver-account-apply.html',
	NW_BUS_FRB_INVESTMENT_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/fixed-term-saver-account-apply.m.html',
	RBS_PER_FRB_INVESTMENT: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/fixed-term-saver-account-apply.html',
	RBS_PER_FRB_INVESTMENT_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/fixed-term-saver-account-apply.m.html',
	RBS_BUS_FRB_INVESTMENT: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/fixed-term-saver-account-apply.html',
	RBS_BUS_FRB_INVESTMENT_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/fixed-term-saver-account-apply.m.html',

	//ListComponent

	RBS_PER_LIST: 'https://personal.rbs.co.uk/personal/security-centre/reporting-fraud.html',
	RBS_PER_LIST_MOB: 'https://personal.rbs.co.uk/personal/security-centre/reporting-fraud.m.html',
	NW_PER_LIST: 'https://personal.natwest.com/personal/security-centre/reporting-fraud.html',
	NW_PER_LIST_MOB: 'https://personal.natwest.com/personal/security-centre/reporting-fraud.m.html',
	NW_PER_LIST_VIEWS: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/reporting-fraud.html',
	NW_PER_LIST_VIEWS_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/reporting-fraud.m.html',
	RBS_PER_LIST_VIEWS: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/reporting-fraud.html',
	RBS_PER_LIST_VIEWS_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/reporting-fraud.m.html',
	NW_BUS_LIST_VIEWS: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/reporting-fraud.html',
	NW_BUS_LIST_VIEWS_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/reporting-fraud.m.html',
	RBS_BUS_LIST_VIEWS: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/reporting-fraud.html',
	RBS_BUS_LIST_VIEWS_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/reporting-fraud.m.html',

	//Mobile Comparision Carousel
	RBS_PER_MOBILE_COMPARISON_CAROUSEL: 'https://personal.rbs.co.uk/personal/savings/compare-savings-accounts.m.html',
	NW_PER_MOBILE_COMPARISON_CAROUSEL: 'https://personal.natwest.com/personal/savings/compare-savings-accounts-new.m.html',
	ULSTER_MOBILE_COMPARISON_CAROUSEL: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/compare-savings-accounts.m.html',
	ULSTER_IE_MOBILE_COMPARISON_CAROUSEL: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/compare-savings-accounts.m.html',
	//LOMBARD_MOBILE_COMPARISON_CAROUSEL:'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/compare-savings-accounts.m.html',
	//LOMBARD_IE_MOBILE_COMPARISON_CAROUSEL:'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/compare-savings-accounts.m.html',
	//RBS_COM_MOBILE_COMPARISON_CAROUSEL:'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/compare-savings-accounts.m.html',
	RBS_BUS_MOBILE_COMPARISON_CAROUSEL: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/compare-savings-accounts.m.html',
	NW_BUS_MOBILE_COMPARISON_CAROUSEL: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/compare-savings-accounts.m.html',
	NW_MARKETS_MOB_COMP_CAROUSEL: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/compare-savings-accounts-new.m.html',
	RBS_PER_TEST_MOBILE_COMPARISON_CAROUSEL: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/compare-savings-accounts.m.html',

	//comparison table
	NW_PER_COMPARISON: 'https://personal.natwest.com/personal/ways-to-bank/post-office.html',
	RBS_PER_COMARISON: 'https://personal.rbs.co.uk/personal/ways-to-bank/post-office.html',
	RBS_REMEMBERS_COMPARISON: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/post-office.html',
	ULSTER_NI_COMPARISON: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/post-office.html',
	ULSTER_ROI_COMPARISON: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/post-office.html',
	LOMBARD_COMPARISON: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/post-office.html',
	NW_BUS_COMPARISON: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/post-office.html',
	RBS_BUS_COMPARISON: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/post-office.html',

	//pdpComparison Table
	NW_PER_PDP_COMPARISON_TABLE: 'https://personal.natwest.com/personal/savings/compare-savings-accounts-new.html',
	RBS_PER_PDP_COMPARISON_TABLE: 'https://personal.rbs.co.uk/personal/savings/compare-savings-accounts.html',
	ULSTER_PDP_COMPARISON_TABLE: 'https://digital.ulsterbank.co.uk/personal/savings.html',
	LMB_COUK_PDP_COMPARISON_TABLE: 'https://www.lombard.co.uk/lombard/products-services/types-of-asset-finance.html',
	ULSTER_BANKIE_PDP_COMPARISON_TABLE: 'https://digital.ulsterbank.ie/personal/current-accounts.html',
	ULSTER_BANKIE_TEST_PDP_COMPARISON_TABLE: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/compare-savings-accounts.html',
	RBS_BUS_TEST_PDP_COMPARISON_TABLE: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/compare-savings-accounts.html',
	NW_BUS_TEST_PDP_COMPARISON_TABLE: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/compare-savings-accounts.html',
	RBS_PER_TEST_PDP_COMPARISON_TABLE: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/compare-savings-accounts.html",
	NW_PER_TEST_PDP_COMPARISON_TABLE: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/compare-savings-accounts.html",
	NW_MAR_TEST_PDP_COMPARISON_TABLE: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/compare-savings-accounts-new.html',

	//OurFallen
	RBS_REM_OUR_FALLEN: 'https://www.rbsremembers.com/remembers/our-fallen.html',
	RBS_REM_OUR_FALLEN_MOBILE: 'https://www.rbsremembers.com/remembers/our-fallen.m.html',

	//TabItem
	RBS_PER_TABITEM_DESKTOP: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/remortgage-to-rbs.html',
	RBS_PER_TABITEM_MOBILE: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/remortgage-to-rbs.m.html',
	RBS_BUS_TABITEM_DESKTOP: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/remortgage-to-rbs.html',
	RBS_BUS_TABITEM_MOBILE: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/remortgage-to-rbs.m.html',
	NW_PER_TABITEM_DESKTOP: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/remortgage-to-rbs.html',
	NW_PER_TABITEM_MOBILE: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/remortgage-to-rbs.m.html',
	NW_BUS_TABITEM_DESKTOP: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/remortgage-to-rbs.html',
	NW_BUS_TABITEM_MOBILE: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/remortgage-to-rbs.m.html',
	RBS_COM_TABITEM_DESKTOP: 'https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/remortgage-to-rbs.html',
	RBS_COM_TABITEM_MOBILE: 'https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/remortgage-to-rbs.m.html',
	LOM_UK_TABITEM_DESKTOP: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/remortgage-to-rbs.html',
	LOM_UK_TABITEM_MOBILE: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/remortgage-to-rbs.m.html',

	//Rating Component
	NW_PER_RATING: "https://personal.natwest.com/personal/life-moments/moving-in-together.html",
	NW_PER_RATING_MOB: "https://personal.natwest.com/personal/life-moments/moving-in-together.m.html",
	RBS_PER_RATING: "https://personal.rbs.co.uk/personal/life-moments/moving-in-together.html",
	RBS_PER_RATING_MOB: "https://personal.rbs.co.uk/personal/life-moments/moving-in-together.m.html",
	NW_MARKETS_RATING: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/ratings.html",
	NW_MARKETS_RATING_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/ratings.m.html",
	RBSCOM_RATING: "https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/ratings.html?sdjknb",
	RBSCOM_RATING_MOB: "https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/ratings.m.html?sdjknb",
	RBS_REMEMBERS_RATING: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/ratings.html",
	RBS_REMEMBERS_RATING_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/ratings.m.html",

	//Blog Component
	RBS_IF_BLOG: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/harper-s-bazaar-article.html",
	RBS_IF_BLOG_MOB: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/harper-s-bazaar-article.m.html",
	RBS_PER_BLOG: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/harper-s-bazaar-article.html",
	RBS_PER_BLOG_MOB: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/harper-s-bazaar-article.m.html",
	RBS_REMEMBERS_BLOG: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/harper-s-bazaar-article.html",
	RBS_REMEMBERS_BLOG_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/harper-s-bazaar-article.m.html",
	RBS_COM_BLOG: "https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/harper-s-bazaar-article.html",
	RBS_COM_BLOG_MOB: "https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/harper-s-bazaar-article.m.html",
	NW_PER_BLOG: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/harper-s-bazaar-article.html",
	NW_PER_BLOG_MOB: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/harper-s-bazaar-article.m.html",
	NW_MARKETS_BLOG: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/harper-s-bazaar-article.html",
	NW_MARKETS_BLOG_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/harper-s-bazaar-article.m.html",
	LOM_UK_BLOG: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/harper-s-bazaar-article.html",
	LOM_UK_BLOG_MOB: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/harper-s-bazaar-article.m.html",
	ULSTER_IE_BLOG: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/harper-s-bazaar-article.html",
	ULSTER_IE_BLOG_MOB: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/harper-s-bazaar-article.m.html",

	//Notification shelf

	NW_PER_NOTIFICATION_SHELF: 'https://personal.natwest.com/personal/insurance/home-insurance.html',
	NW_PER_NOTIFICATION_SHELF_MOB: 'https://personal.natwest.com/personal/insurance/home-insurance.m.html',
	NW_PER_CURR_ACC_NOTIFICATION_SHELF: 'https://personal.natwest.com/personal/current-accounts/overdrafts/change-or-remove-your-arranged-overdraft.html',
	NW_PER_CURR_ACC_NOTIFICATION_SHELF_MOB: 'https://personal.natwest.com/personal/current-accounts/overdrafts/change-or-remove-your-arranged-overdraft.m.html',
	NW_PER_NOTIFICATION_SHELF1: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.html',
	NW_PER_NOTIFICATION_SHELF1_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.m.html',
	NW_MARKETS_NOTIFICATION_SHELF: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/notificationShelf1.html',
	NW_MARKETS_NOTIFICATION_SHELF_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/notificationShelf1.m.html',
	NW_BUS_NOTIFICATION_SHELF: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/notificationShelf1.html',
	NW_BUS_NOTIFICATION_SHELF_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/notificationShelf1.m.html',
	RBS_PER_NOTIFICATION_SHELF: 'https://personal.rbs.co.uk/personal/insurance/home-insurance.html',
	RBS_PER_NOTIFICATION_SHELF_MOB: 'https://personal.rbs.co.uk/personal/insurance/home-insurance.m.html',
	RBS_PER_CURR_ACC_NOTIFICATION_SHELF: 'https://personal.rbs.co.uk/personal/current-accounts/overdrafts/change-or-remove-your-arranged-overdraft.html',
	RBS_PER_CURR_ACC_NOTIFICATION_SHELF_MOB: 'https://personal.rbs.co.uk/personal/current-accounts/overdrafts/change-or-remove-your-arranged-overdraft.m.html',
	RBS_PER_NOTIFICATION_SHELF1: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.html',
	RBS_PER_NOTIFICATION_SHELF1_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.m.html',
	RBS_BUS_NOTIFICATION_SHELF: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/notificationShelf1.html',
	RBS_BUS_NOTIFICATION_SHELF_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/notificationShelf1.m.html',
	RBS_COM_NOTIFICATION_SHELF: 'https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/notificationShelf1.html',
	RBS_COM_NOTIFICATION_SHELF_MOB: 'https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/notificationShelf1.m.html',
	RBS_REMEMBERS_NOTIFICATION_SHELF: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/notificationShelf1.html',
	RBS_REMEMBERS_NOTIFICATION_SHELF_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/notificationShelf1.m.html',
	ULSTER_COUK_NOTIFICATION_SHELF: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.html',
	ULSTER_IE_NOTIFICATION_SHELF: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.html',
	ULSTER_COUK_NOTIFICATION_SHELF_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.m.html',
	ULSTER_IE_NOTIFICATION_SHELF_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/notificationShelf1.m.html',
	LOMBARD_COUK_NOTIFICATION_SHELF: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/notificationShelf1.html',
	LOMBARD_COUK_NOTIFICATION_SHELF_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/notificationShelf1.m.html',
	LOMBARD_IE_NOTIFICATION_SHELF: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/notificationShelf1.html',
	LOMBARD_IE_NOTIFICATION_SHELF_MOB: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/notificationShelf1.m.html",
	NW_PER_SUBNAV: 'https://personal.natwest.com/personal/savings/compare-savings-accounts-new.html',

	//automated list 
	RBS_COM_AUTOMATED_LIST: 'https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/women-in-banking.html',
	RBS_COM_AUTOMATED_LIST_MOB: 'https://rbscom-nfte1.arete.managedtest.com/heritage/wscautomation/women-in-banking.m.html',

	//brandhighlights

	RBS_COM_BRANDHIGHTLIGHTS_NW: 'https://www.rbs.com/rbs/our-brands/natwest.html',
	RBS_COM_BRANDHIGHTLIGHTS_NW_MOB: 'https://www.rbs.com/rbs/our-brands/natwest.m.html',
	RBS_COM_BRANDHIGHTLIGHTS_RBS: 'https://www.rbs.com/rbs/our-brands/royal-bank-of-scotland.html',
	RBS_COM_BRANDHIGHTLIGHTS_RBS_MOB: 'https://www.rbs.com/rbs/our-brands/royal-bank-of-scotland.m.html',
	RBS_COM_BRANDHIGHTLIGHTS_ULSTER: 'https://www.rbs.com/rbs/our-brands/ulster-bank.html',
	RBS_COM_BRANDHIGHTLIGHTS_ULSTER_MOB: 'https://www.rbs.com/rbs/our-brands/ulster-bank.m.html',

	//tool hero 
	NW_PER_TOOL_HERO: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/how-much-can-i-borrow.html',
	NW_PER_TOOL_HERO_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/how-much-can-i-borrow.m.html',
	RBS_PER_TOOL_HERO: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/debt-options.html',
	RBS_PER_TOOL_HERO_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/debt-options.m.html',
	ULSTER_NI_TOOL_HERO: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/how-much-can-i-borrow.html',
	ULSTER_NI_TOOL_HERO_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/how-much-can-i-borrow.m.html',
	ULSTER_ROI_TOOL_HERO: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/how-much-can-i-borrow.html',
	ULSTER_ROI_TOOL_HERO_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/how-much-can-i-borrow.m.html',


	//blog header
	RBSIF_COUK_BLOGHEADER: 'https://www.rbsif.co.uk/invoice-finance/about/news/invoice-finance-smes-rises-to-711-m.html',
	RBS_PER_BLOGHEADER: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.html',
	NW_PER_BLOGHEADER: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.html',
	NW_BUS_BLOGHEADER: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/things-to-think-about.html',
	RBS_BUS_BLOGHEADER: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/things-to-think-about.html',
	UL_COUK_BLOGHEADER: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.html',
	UL_IE_BLOGHEADER: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.html',
	LOM_COUK_BLOGHEADER: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/things-to-think-about.html',
	NW_MKTS_BLOGHEADER: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/things-to-think-about.html',
	RBSIF_COUK_BLOGHEADER_MOB: 'https://www.rbsif.co.uk/invoice-finance/about/news/invoice-finance-smes-rises-to-711-m.m.html',
	RBS_PER_BLOGHEADER_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.m.html',
	NW_PER_BLOGHEADER_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.m.html',
	NW_BUS_BLOGHEADER_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/things-to-think-about.m.html',
	RBS_BUS_BLOGHEADER_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/things-to-think-about.m.html',
	UL_COUK_BLOGHEADER_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.m.html',
	UL_IE_BLOGHEADER_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/things-to-think-about.m.html',
	LOM_COUK_BLOGHEADER_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/things-to-think-about.m.html',
	NW_MKTS_BLOGHEADER_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/things-to-think-about.m.html',

	//grcSharePrice
	RBS_COM_GCR_SHARE_PRICE: "https://www.rbs.com/",
	RBS_COM_GCR_SHARE_PRICE_M: 'https://www.rbs.com/rbs/our-brands.m.html',

	//Product Details Shelf
	RBS_PER_PRODUCTDETAILS: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.html",
	RBS_PER_PRODUCTDETAILS_MOB: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.m.html",
	RBS_BUS_PRODUCTDETAILS: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/productdetailshub.html",
	RBS_BUS_PRODUCTDETAILS_MOB: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/productdetailshub.m.html",
	NW_PER_PRODUCTDETAILS: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.html",
	NW_PER_PRODUCTDETAILS_MOB: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.m.html",
	NW_BUS_PRODUCTDETAILS: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/productdetailshub.html",
	NW_BUS_PRODUCTDETAILS_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/productdetailshub.m.html",
	LMB_CO_UK_PRODUCTDETAILS: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/productdetailshub.html",
	LMB_CO_UK_PRODUCTDETAILS_MOB: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/productdetailshub.m.html",
	LMB_IE_PRODUCTDETAILS: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/productdetailshub.html",
	LMB_IE_PRODUCTDETAILS_MOB: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/productdetailshub.m.html",
	RBS_REM_PRODUCTDETAILS: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/productdetailshub.html",
	RBS_REM_PRODUCTDETAILS_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/productdetailshub.m.html",
	NW_MAR_PRODUCTDETAILS: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/productdetailshub.html",
	NW_MAR_PRODUCTDETAILS_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/productdetailshub.m.html",
	RBS_COM_PRODUCTDETAILS: "https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/productdetailshub.html",
	RBS_COM_PRODUCTDETAILS_MOB: "https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/productdetailshub.m.html",
	ULSTER_COM_PRODUCTDETAILS: "https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.html",
	ULSTER_COM_PRODUCTDETAILS_MOB: "https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.m.html",
	ULSTER_IE_PRODUCTDETAILS: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.html",
	ULSTER_IE_PRODUCTDETAILS_MOB: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/productdetailshub.m.html",


	//SocialToolbar
NW_PER_SOCIAL_TOOLBAR: 'https://personalnatwestcom-dev3.arete.managedtest.com/personal/current-accounts/overdrafts/apply-for-a-graduate-overdraft.html',
NW_PER_NEW_REBRAND_SOCIAL_TOOLBAR: 'https://personal.natwest.com/personal/savings/manage-your-savings.html',
NW_PER_SOCIAL_TOOLBAR_M: 'https://personal.natwest.com/personal/savings/compare-savings-accounts-new.m.html',
NW_PER_SOCIAL_TOOLBAR1_M: 'https://personal.natwest.com/personal/savings/manage-your-savings.m.html',
RBS_PER__SOCIAL_TOOLBAR: 'https://personal.rbs.co.uk/personal/current-accounts/manage.html',
RBS_PER__SOCIAL_TOOLBAR_M: 'https://personal.rbs.co.uk/personal/current-accounts/manage.m.html',
RBS_PER__SOCIAL_TOOLBAR1: 'https://personal.rbs.co.uk/personal/myrewards/partner-retailers.html',
RBS_PER__SOCIAL_TOOLBAR1_M: 'https://personal.rbs.co.uk/personal/myrewards/partner-retailers.m.html',
RBS_PER_REB__SOCIAL_TOOLBAR: 'https://personal.rbs.co.uk/personal/savings/manage-your-savings.html',
RBS_PER_REB__SOCIAL_TOOLBAR_M: 'https://personal.rbs.co.uk/personal/savings/manage-your-savings.m.html',


ULSTER_IE_SOCIAL_TOOLBAR: 'https://digital.ulsterbank.ie/business/accounts-and-services/business-current-accounts/business-current-account.html',
ULSTER_IE_SOCIAL_TOOLBAR_M: 'https://digital.ulsterbank.ie/business/accounts-and-services/business-current-accounts/business-current-account.m.html',
ULSTER_COOUK_SOCIAL_TOOLBAR: 'https://digital.ulsterbank.co.uk/personal/mortgages/manage-your-ulster-bank-mortgage.html',
ULSTER_COOUK_SOCIAL_TOOLBAR_M: 'https://digital.ulsterbank.co.uk/personal/mortgages/manage-your-ulster-bank-mortgage.m.html',

	//blogauthor component 
	
	NW_PER_BLOGAUTHOR:'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	NW_PER_BLOGAUTHOR_MOB:'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	NW_BUS_BLOGAUTHOR:'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/author_blog.html',
	NW_BUS_BLOGAUTHOR_MOB:'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/author_blog.m.html',
	RBS_PER_BLOGAUTHOR:'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	RBS_PER_BLOGAUTHOR_MOB:'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	RBS_BUS_BLOGAUTHOR:'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/author_blog.html',
	RBS_BUS_BLOGAUTHOR_MOB:'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/author_blog.m.html',
	ULSTER_COUK_BLOGAUTHOR:'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	ULSTER_COUK_BLOGAUTHOR_MOB:'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	ULSTER_IE_BLOGAUTHOR:'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	ULSTER_IE_BLOGAUTHOR_MOB:'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	LOMBARD_COUK_BLOGAUTHOR:'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/author_blog.html',
	LOMBARD_COUK_BLOGAUTHOR_MOB:'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/author_blog.m.html',
	LOMBARD_IE_BLOGAUTHOR:'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/author_blog.html',
	LOMBARD_IE_BLOGAUTHOR_MOB:'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/author_blog.m.html',
	RBSIF_COUK_BLOGAUTHOR:'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/author_blog.html',
	RBSIF_COUK_BLOGAUTHOR_MOB:'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/author_blog.m.html',
	RBSCOM_BLOGAUTHOR:'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/author_blog.html',
	RBSCOM_BLOGAUTHOR_MOB:'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/author_blog.m.html',
	NW_MARKETS_BLOGAUTHOR:'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/author_blog.html',
	NW_MARKETS_BLOGAUTHOR_MOB:'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/author_blog.m.html',
	RBS_REMEMBERS_BLOGAUTHOR:'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/author_blog.html',
	RBS_REMEMBERS_BLOGAUTHOR_MOB:'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/author_blog.m.html',
	NW_INTERMEDIARY_BLOGAUTHOR :'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/author_blog.html',
	NW_INTERMEDIARY_BLOGAUTHOR_MOB:'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/author_blog.m.html',

	NW_PER_BLOGAUTHOR: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	NW_PER_BLOGAUTHOR_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	NW_BUS_BLOGAUTHOR: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/author_blog.html',
	NW_BUS_BLOGAUTHOR_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/author_blog.m.html',
	RBS_PER_BLOGAUTHOR: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	RBS_PER_BLOGAUTHOR_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	RBS_BUS_BLOGAUTHOR: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/author_blog.html',
	RBS_BUS_BLOGAUTHOR_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/author_blog.m.html',
	ULSTER_COUK_BLOGAUTHOR: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	ULSTER_COUK_BLOGAUTHOR_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	ULSTER_IE_BLOGAUTHOR: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.html',
	ULSTER_IE_BLOGAUTHOR_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wscautomation/author_blog.m.html',
	LOMBARD_COUK_BLOGAUTHOR: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/author_blog.html',
	LOMBARD_COUK_BLOGAUTHOR_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wscautomation/author_blog.m.html',
	LOMBARD_IE_BLOGAUTHOR: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/author_blog.html',
	LOMBARD_IE_BLOGAUTHOR_MOB: 'https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/author_blog.m.html',
	RBSIF_COUK_BLOGAUTHOR: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/author_blog.html',
	RBSIF_COUK_BLOGAUTHOR_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/author_blog.m.html',
	RBSCOM_BLOGAUTHOR: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/author_blog.html',
	RBSCOM_BLOGAUTHOR_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wscautomation/author_blog.m.html',
	NW_MARKETS_BLOGAUTHOR: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/author_blog.html',
	NW_MARKETS_BLOGAUTHOR_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/author_blog.m.html',
	RBS_REMEMBERS_BLOGAUTHOR: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/author_blog.html',
	RBS_REMEMBERS_BLOGAUTHOR_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/author_blog.m.html',
	NW_INTERMEDIARY_BLOGAUTHOR: 'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/author_blog.html',
	NW_INTERMEDIARY_BLOGAUTHOR_MOB: 'https://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/author_blog.m.html',
	// Tiles
	NW_PER_TILE: 'https://personal.natwest.com/personal/life-moments.html',
	NW_PER_TILE_M: 'https://personal.natwest.com/personal/life-moments.m.html',
	RBS_PER_TILE: 'https://personal.rbs.co.uk/personal/life-moments.html',
	RBS_PER_TILE_M: 'https://personal.rbs.co.uk/personal/life-moments.m.html',
	NW_BUS_TILE: 'https://www.business.natwest.com/business/Boost/business-matters.html',
	NW_BUS_TILE_M: 'https://www.business.natwest.com/business/Boost/business-matters.m.html',
	RBS_BUS_TILE: 'https://www.business.rbs.co.uk/business/Boost/business-matters.html',
	RBS_BUS_TILE_M: 'https://www.business.rbs.co.uk/business/Boost/business-matters.m.html',
	NW_MARKETS_TILE: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/life-moments.html',
	NW_MARKETS_TILE_M: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/life-moments.m.html',

	//frb-investment
	NW_PER_FRB_INVESTMENT: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/fixed-term-saver-account-apply.html',
	NW_PER_FRB_INVESTMENT_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/fixed-term-saver-account-apply.m.html',
	NW_BUS_FRB_INVESTMENT: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/fixed-term-saver-account-apply.html',
	NW_BUS_FRB_INVESTMENT_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/fixed-term-saver-account-apply.m.html',
	RBS_PER_FRB_INVESTMENT: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/fixed-term-saver-account-apply.html',
	RBS_PER_FRB_INVESTMENT_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/fixed-term-saver-account-apply.m.html',
	RBS_BUS_FRB_INVESTMENT: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/fixed-term-saver-account-apply.html',
	RBS_BUS_FRB_INVESTMENT_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/frb_inv_mob.m.html',
	RBS_REM_FRB_INVESTMENT: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/fixed-term-saver-account-apply.html',
	RBS_REM_FRB_INVESTMENT_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/fixed-term-saver-account-apply.m.html',
	ULSTER_NI_FRB_INVESTMENT: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/fixed-term-saver-account-apply.html',
	ULSTER_NI_FRB_INVESTMENT_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/fixed-term-saver-account-apply.m.html',
	ULSTER_ROI_FRB_INVESTMENT: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/fixed-term-saver-account-apply.html	',
	ULSTER_ROI_FRB_INVESTMENT_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/fixed-term-saver-account-apply.m.html',

	//apr
	NW_PER_APR: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_repex.html',
	NW_PER_APR_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_repex.m.html',
	NW_BUS_APR: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_repex.html',
	NW_BUS_APR_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_repex.m.html',
	LOMBARD_COUK_APR: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test_repex.html',
	LOMBARD_COUK_APR_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test_repex.m.html',
	RBS_PER_APR: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_repex.html',
	RBS_PER_APR_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_repex.m.html',
	RBS_BUS_APR: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_repex.html',
	RBS_BUS_APR_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_repex.m.html',
	RBS_COM_APR: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_repex.html',
	RBS_COM_APR_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_repex.m.html',

	//Text Image
	NW_PER_TXTIMG: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/text_image.html',
	NW_PER_TXTIMG_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/text_image.m.html',
	RBS_PER_TXTIMG: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/text_image.html",
	RBS_PER_TXTIMG_MOB: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wscautomation/text_image.m.html",
	NW_MARKETS_TXTIMG: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/text_image.html",
	NW_MARKETS_TXTIMG_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wscautomation/text_image.m.html",
	NW_INTERMEDIARY_TXTIMG: "http://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/text_image.html",
	NW_INTERMEDIARY_TXTIMG_MOB: "http://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/wscautomation/text_image.m.html",
	NW_BUS_TXTIMG: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/text_image.html",
	NW_BUS_TXTIMG_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wscautomation/text_image.m.html",
	RBS_BUS_TXTIMG: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/text_image.html",
	RBS_BUS_TXTIMG_MOB: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wscautomation/text_image.m.html",
	RBS_REM_TXTIMG: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/text_image.html",
	RBS_REM_TXTIMG_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wscautomation/text_image.m.html",
	LOM_IE_TXTIMG: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/text_image.html",
	LOM_IE_TXTIMG_MOB: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wscautomation/text_image.m.html",
	RBS_IF_TXTIMG: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/text_image.html",
	RBS_IF_TXTIMG_MOB: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wscautomation/text_image.m.html",

	//Header Natwest Logo
	NW_BUS_HEADERLOGO: "https://natwestcom-dev2.arete.managedtest.com/business/main/landing_page.html",
	NW_BUS_HEADERLOGO_MOB: "https://personalnatwestcom-dev2.arete.managedtest.com/business/main/spoke.m.html",
	NW_BUS_HEADERLOGO_WHITE: "https://www.business.natwest.com/business/Business-Cards/Online-solutions-business-credit-card.html",
	NW_PER_HEADERLOGO: "https://natwestcom-dev2.arete.managedtest.com/personal/main/hub_page.html",
	NW_PER_HEADERLOGO_MOB: "https://natwestcom-dev2.arete.managedtest.com/personal/header_logo/spoke.m.html",
	NW_PER_HEADERLOGO_WHITE: "https://natwestcom-dev2.arete.managedtest.com/personal/header_logo/spoke.html",
	NW_PRIVATE_HEADERLOGO: "https://natwestcom-sit2.arete.managedtest.com/private/csp-testing.html",
	NW_PRIVATE_HEADERLOGO_MOB: "https://natwestcom-sit2.arete.managedtest.com/private/csp-testing.m.html",
	NW_PRIVATE_HEADERLOGO_WHITE: "https://natwestcom-dev2.arete.managedtest.com/private/main/spoke.html",

	//Video
	NW_PER_VIDEO: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_video.html",
	NW_PER_VIDEO_MOB: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_video.m.html",
	NW_MARKETS_VIDEO: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_video.html",
	NW_MARKETS_VIDEO_MOB: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_video.m.html",
	NW_BUS_VIDEO: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_video.html",
	NW_BUS_VIDEO_MOB: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_video.m.html",
	RBS_PER_VIDEO: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_video.html",
	RBS_PER_VIDEO_MOB: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_video.m.html",
	RBS_COM_VIDEO: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_video.html",
	RBS_COM_VIDEO_MOB: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_video.m.html",
	RBS_REMEMBERS_VIDEO: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_video.html",
	RBS_REMEMBERS_VIDEO_MOB: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_video.m.html",
	RBS_IF_VIDEO: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_video.html",
	RBS_IF_VIDEO_MOB: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_video.m.html",
	RBS_BUS_VIDEO: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_video.html",
	RBS_BUS_VIDEO_MOB: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_video.m.html",
	ULSTER_COUK_VIDEO_DESKTOP: "https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test_video.html",
	ULSTER_COUK_VIDEO_MOB: "https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/test_video.m.html",
	ULSTER_IE_VIDEO_DESKTOP: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test_video.html",
	ULSTER_IE_VIDEO_MOB: "https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/test_video.m.html",

	//Light-box
	NW_PER_LightBox: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_lightbox.html',
	NW_PER_LightBox_M: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/test_lightbox.m.html',

	//Video Caraousel 
	NW_PER_VIDEOCARAOUSEL_DESKTOP: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/test_carousel.html",
	NW_PER_VIDEOCARAOUSEL_MOBILE: "https://personalnatwestcom-nfte1.arete.managedtest.com/personal/test_carousel.m.html",
	NW_BUS_VIDEOCARAOUSEL_DESKTOP: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_carousel.html",
	NW_BUS_VIDEOCARAOUSEL_MOBILE: "https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/test_carousel.m.html",
	NW_MAR_VIDEOCARAOUSEL_DESKTOP: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_carousel.html",
	NW_MAR_VIDEOCARAOUSEL_MOBILE: "https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/test_carousel.m.html",
	RBS_PER_VIDEOCARAOUSEL_DESKTOP: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_carousel.html",
	RBS_PER_VIDEOCARAOUSEL_MOBILE: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/test_carousel.m.html",
	RBS_COM_VIDEOCARAOUSEL_DESKTOP: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_carousel.html",
	RBS_COM_VIDEOCARAOUSEL_MOBILE: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_carousel.m.html",
	RBS_BUS_VIDEOCARAOUSEL_DESKTOP: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_carousel.html",
	RBS_BUS_VIDEOCARAOUSEL_MOBILE: "https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/test_carousel.m.html",
	RBS_REM_VIDEOCARAOUSEL_DESKTOP: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_carousel.html",
	RBS_REM_VIDEOCARAOUSEL_MOBILE: "https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/test_carousel.m.html",
	RBS_IF_VIDEOCARAOUSEL_DESKTOP: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_carousel.html",
	RBS_IF_VIDEOCARAOUSEL_MOBILE: "https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/test_carousel.m.html	",
	LOM_COUK_VIDEOCARAOUSEL_DESKTOP: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test_carousel.html",
	LOM_COUK_VIDEOCARAOUSEL_MOBILE: "https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/test_carousel.m.html",
	LOM_IE_VIDEOCARAOUSEL_DESKTOP: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_carousel.html",
	LOM_IE_VIDEOCARAOUSEL_MOBILE: "https://lombardie-nfte1.arete.managedtest.com/lombard-ireland/wsctest/test_carousel.m.html",

	//Qumu Video

	RBS_COM_QUMU_DESKTOP: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_qumuvideo.html",
	RBS_COM_QUMU_MOBILE: "https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/test_qumuvideo.m.html",

	//Hero Shelf Component 

	NW_PER_HERO_SHELF1: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/hub_hero.html',
	NW_PER_HERO_SHELF1_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/hub_hero.m.html',
	NW_PER_HERO_SHELF2: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/land_hero.html',
	NW_PER_HERO_SHELF2_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/land_hero.m.html',
	NW_PER_HERO_SHELF3: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_hplp.html',
	NW_PER_HERO_SHELF3_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_hplp.m.html',
	NW_PER_HERO_SHELF4: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_spoke.html',
	NW_PER_HERO_SHELF4_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_spoke.m.html',
	NW_PER_HERO_SHELF5: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_tool.html',
	NW_PER_HERO_SHELF5_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_tool.m.html',
	NW_PER_HERO_SHELF6: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_land.html',
	NW_PER_HERO_SHELF6_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_land.m.html',
	NW_PER_HERO_SHELF7: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_hub.html',
	NW_PER_HERO_SHELF7_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/rebrandhero_hub.m.html',
	NW_PER_HERO_SHELF8: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp.html',
	NW_PER_HERO_SHELF8_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp.m.html',
	NW_PER_HERO_SHELF9: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp1.html',
	NW_PER_HERO_SHELF9_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp1.m.html',
	NW_PER_HERO_SHELF10: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp2.html',
	NW_PER_HERO_SHELF10_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp2.m.html',
	NW_PER_HERO_SHELF11: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp3.html',
	NW_PER_HERO_SHELF11_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp3.m.html',
	NW_PER_HERO_SHELF12: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp4.html',
	NW_PER_HERO_SHELF12_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/hero_hplp4.m.html',	//Cookie
	NW_PER_COOKIE: 'https://personalnatwestcom-nfte1.arete.managedtest.com/',
	LOM_COUK_COOKIE: 'https://lombardcouk-nfte1.arete.managedtest.com/',
	RBS_PER_COOKIE: 'https://personalrbscouk-nfte1.arete.managedtest.com/',
	RBSCOM_COOKIE: 'https://rbscom-nfte1.arete.managedtest.com/',
	NW_BUS_COOKIE: 'https://businessnatwestcom-nfte1.arete.managedtest.com/',
	RBS_BUS_COOKIE: 'https://businessrbscouk-nfte1.arete.managedtest.com/',
	UL_COUK_COOKIE: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/',
	UL_IE_COOKIE: 'https://ulsterbankie-nfte1.arete.managedtest.com/',
	RBSIF_COOKIE: 'https://rbsifcouk-nfte1.arete.managedtest.com/',
	NW_MKTS_COOKIE: 'https://natwestmarketscom-nfte1.arete.managedtest.com/',
	NW_INT_COOKIE: 'http://intermediarynatwestcom-nfte1.arete.managedtest.com/',
	RBS_REM_COOKIE: 'https://rbsrememberscom-nfte1.arete.managedtest.com/',
	NW_PER_COOKIE_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/personal.m.html',
	LOM_COUK_COOKIE_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/reporting-fraud.m.html',
	RBS_PER_COOKIE_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/personal.m.html',
	RBSCOM_COOKIE_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/about/the_bank_we_are_becoming.m.html',
	NW_BUS_COOKIE_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com//business/ways-to-bank/bankline.m.html',
	RBS_BUS_COOKIE_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/business/rbs-business-bankingsupportcentre/change-order.m.html',
	UL_COUK_COOKIE_MOB: 'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal.m.html',
	UL_IE_COOKIE_MOB: 'https://ulsterbankie-nfte1.arete.managedtest.com/personal.m.html',
	RBSIF_COOKIE_MOB: 'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/products-services/invoice-discounting.m.html',
	NW_MKTS_COOKIE_MOB: 'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/about-us.m.html',
	NW_INT_COOKIE_MOB: 'http://intermediarynatwestcom-nfte1.arete.managedtest.com/intermediary-solutions/products.m.html',
	RBS_REM_COOKIE_MOB: 'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/our-people/behind-the-counter.m.html',

	//COOKIE CONSENT
	RBS_PER_COOKIECONSENT: 'https://personalrbscouk-nfte1.arete.managedtest.com/cc-check.html',
	NW_PER_COOKIECONSENT: 'https://personalnatwestcom-nfte1.arete.managedtest.com/cc-check.html',
	NW_BUS_COOKIECONSENT: 'https://businessnatwestcom-nfte1.arete.managedtest.com/cc-check.html',
	RBS_BUS_COOKIECONSENT: 'https://businessrbscouk-nfte1.arete.managedtest.com/cc-check.html',
	LOM_COUK_COOKIECONSENT: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/cc-check.html',
	RBS_COM_COOKIECONSENT: 'https://rbscom-nfte1.arete.managedtest.com/rbs/cc-check.html',
	RBS_PER_COOKIECONSENT_MOB: 'https://personalrbscouk-nfte1.arete.managedtest.com/cc-check.m.html',
	NW_PER_COOKIECONSENT_MOB: 'https://personalnatwestcom-nfte1.arete.managedtest.com/cc-check.m.html',
	NW_BUS_COOKIECONSENT_MOB: 'https://businessnatwestcom-nfte1.arete.managedtest.com/cc-check.m.html',
	RBS_BUS_COOKIECONSENT_MOB: 'https://businessrbscouk-nfte1.arete.managedtest.com/cc-check.m.html',
	LOM_COUK_COOKIECONSENT_MOB: 'https://lombardcouk-nfte1.arete.managedtest.com/lombard/cc-check.m.html',
    RBS_COM_COOKIECONSENT_MOB : 'https://rbscom-nfte1.arete.managedtest.com/rbs/cc-check.m.html',

	//Supplier LookUp 
	NW_PER_SUPPLIERLOOKUP: "https://personal.natwest.com/personal/current-accounts/compare-current-accounts/supplier-tool.html",
	RBS_PER_SUPPLIERLOOKUP: "https://personal.rbs.co.uk/personal/current-accounts/compare-current-accounts/supplier-tool.html",
	NW_PER_SUPPLIERLOOKUP_MOB: "https://personal.natwest.com/personal/current-accounts/compare-current-accounts/supplier-tool.m.html",
	RBS_PER_SUPPLIERLOOKUP_MOB: "https://personal.rbs.co.uk/personal/current-accounts/compare-current-accounts/supplier-tool.m.html",
	RBS_COM_COOKIECONSENT_MOB: 'https://rbscom-nfte1.arete.managedtest.com/rbs/cc-check.m.html',
	//BORROWING NEEDS TOOL
	NW_PER_BORROWING_NEEDS: "https://tools.natwest.com/personal/borrowing-needs/borrowing-needs.html",
	RBS_PER_BORROWING_NEEDS: "https://www.tools-rbs.co.uk/personal/borrowing-needs/borrowing-needs.html",
	NW_PER_BORROWING_NEEDS_MOB: "https://tools.natwest.com/personal/borrowing-needs/borrowing-needs.m.html",
	RBS_PER_BORROWING_NEEDS_MOB: "https://www.tools-rbs.co.uk/personal/borrowing-needs/borrowing-needs.m.html",
	//BTL
	NW_PER_BTL:"https://personalnatwestcom-nfte1.arete.managedtest.com/personal/mortgages/secure/buy-to-let-mortgages-agreement-in-principle.html",
	RBS_PER_BTL:"https://personalrbscouk-nfte1.arete.managedtest.com/personal/mortgages/secure/buy-to-let-mortgages-agreement-in-principle.html",

	//budget calculator 
	RBS_PER_BUDGET_CALC: 'https://personal.rbs.co.uk/personal/life-moments/managing-your-money/budget-calculator.html',
	RBS_PER_BUDGET_CALC_MOB: 'https://personal.rbs.co.uk/personal/life-moments/managing-your-money/budget-calculator.m.html',
	NW_PER_BUDGET_CALC: 'https://personal.natwest.com/personal/life-moments/managing-your-money/budget-calculator.html',
	NW_PER_BUDGET_CALC_MOB: 'https://personal.natwest.com/personal/life-moments/managing-your-money/budget-calculator.m.html',
	//MOPC Tool 

	RBS_MOPC: 'https://personal.rbs.co.uk/personal/mortgages/mortgage-calculators/mortgage-overpayment-tool.html',
	NW_MOPC: 'https://personal.natwest.com/personal/mortgages/mortgage-calculators/mortgage-overpayment-tool.html',
	ULSTER_IE_MOPC: 'https://digital.ulsterbank.ie/personal/mortgages/secure/mortgage-overpayment-tool.html',
	RBS_MOPC_MOB: 'https://personal.rbs.co.uk/personal/mortgages/mortgage-calculators/mortgage-overpayment-tool.m.html',
	NW_MOPC_MOB: 'https://personal.natwest.com/personal/mortgages/mortgage-calculators/mortgage-overpayment-tool.m.html',
	ULSTER_IE_MOPC_MOB: 'https://digital.ulsterbank.ie/personal/mortgages/secure/mortgage-overpayment-tool.m.html',


	//Mortgage Rate Finder Tool

	NW_PER_MRF: 'https://personal.natwest.com/personal/mortgages/mortgage-calculators/mortgage-rate-finder-mortgage-calculator.html',
	RBS_PER_MRF: 'https://personal.rbs.co.uk/personal/mortgages/mortgage-calculators/mortgagefinder.html',
	NW_PER_MRF_MOB: 'https://personal.natwest.com/personal/mortgages/mortgage-calculators/mortgage-rate-finder-mortgage-calculator.m.html',
	RBS_PER_MRF_MOB: 'https://personal.rbs.co.uk/personal/mortgages/mortgage-calculators/mortgagefinder.m.html',


	//Agreement in Principle (AIP)
	NW_PERSONAL_AIP_DESKTOP: "https://personal.natwest.com/personal/mortgages/secure/mortgage-agreement-in-principle.html",
	RBS_PERSONAL_AIP_DESKTOP: "https://personalrbscouk-nfte1.arete.managedtest.com/personal/mortgages/secure/mortgage-agreement-in-principle.html ",


	//hmcib tool
	NW_PER_HMCIB: "https://personal.natwest.com/personal/mortgages/mortgage-calculators/how-much-can-i-borrow.html",
	NW_PER_HMCIB_MOB: "https://personal.natwest.com/personal/mortgages/mortgage-calculators/how-much-can-i-borrow.m.html",
	RBS_PER_HMCIB: "https://personal.rbs.co.uk/personal/mortgages/mortgage-calculators/how-much-can-i-borrow.html",
	RBS_PER_HMCIB_MOB: "https://personal.rbs.co.uk/personal/mortgages/mortgage-calculators/how-much-can-i-borrow.m.html",
	IOM_HMCIB: "https://tools.iombank.com/iom/mortgages/tools/secure/how-much-can-i-borrow.html",
	IOM_HMCIB_MOB: "https://tools.iombank.com/iom/mortgages/tools/secure/how-much-can-i-borrow.m.html",
	NW_INTER_HMCIB: "https://natwestinternationalcom-nfte1.arete.managedtest.com/personal/international/mortgages/jersey/tools/secure/how-much-can-i-borrow.html",
	NW_INTER_HMCIB_MOB: "https://natwestinternationalcom-nfte1.arete.managedtest.com/personal/international/mortgages/jersey/tools/secure/how-much-can-i-borrow.m.html",

	//Buy-to-Let (BTL)
	NW_PER_BTL:"https://personalnatwestcom-nfte1.arete.managedtest.com/personal/mortgages/secure/buy-to-let-mortgages-agreement-in-principle.html",
	RBS_PER_BTL:"https://personalrbscouk-nfte1.arete.managedtest.com/personal/mortgages/secure/buy-to-let-mortgages-agreement-in-principle.html",
	//Tool Shelf
	NW_PER_TOOL_SHELF:'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/tool_shelf.html',
	NW_PER_TOOL_SHELF_MOB:'https://personalnatwestcom-nfte1.arete.managedtest.com/personal/wscautomation/tool_shelf.m.html',
	NW_BUS_TOOL_SHELF:'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/tool_shelf.html',
	NW_BUS_TOOL_SHELF_MOB:'https://businessnatwestcom-nfte1.arete.managedtest.com/business/wsctest/tool_shelf.m.html',
	NW_MARK_TOOL_SHELF:'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/tool_shelf.html',
	NW_MARK_TOOL_SHELF_MOB:'https://natwestmarketscom-nfte1.arete.managedtest.com/natwest-markets/wsctest/tool_shelf.m.html',
	RBS_PER_TOOL_SHELF:'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/tool_shelf.html',
	RBS_PER_TOOL_SHELF_MOB:'https://personalrbscouk-nfte1.arete.managedtest.com/personal/wsctest/tool_shelf.m.html',
	RBS_COM_TOOL_SHELF:'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/tool_shelf.html',
	RBS_COM_TOOL_SHELF_MOB:'https://rbscom-nfte1.arete.managedtest.com/rbs/wsctest/tool_shelf.m.html',
	RBS_BUS_TOOL_SHELF:'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/tool_shelf.html',
	RBS_BUS_TOOL_SHELF_MOB:'https://businessrbscouk-nfte1.arete.managedtest.com/business/wsctest/tool_shelf.m.html',
	RBS_REMEMBERS_TOOL_SHELF:'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/tool_shelf.html',
	RBS_REMEMBERS_TOOL_SHELF_MOB:'https://rbsrememberscom-nfte1.arete.managedtest.com/remembers/wsctest/tool_shelf.m.html',
	RBS_IFCOUK_TOOL_SHELF:'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/tool_shelf.html',
	RBS_IFCOUK_TOOL_SHELF_MOB:'https://rbsifcouk-nfte1.arete.managedtest.com/invoice-finance/wsctest/tool_shelf.m.html',
	LOM_COUK_TOOL_SHELF:'https://lombardcouk-nfte1.arete.managedtest.com/lombard/wsctest/tool_shelf.html',
	UL_COUK_TOOL_SHELF:'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/tool_shelf.html',
	UL_COUK_TOOL_SHELF_MOB:'https://ulsterbankcouk-nfte1.arete.managedtest.com/personal/wsctest/tool_shelf.m.html',
	UL_IE_TOOL_SHELF:'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/tool_shelf.html',
	UL_IE_TOOL_SHELF_MOB:'https://ulsterbankie-nfte1.arete.managedtest.com/personal/wsctest/tool_shelf.m.html',	

  //merchant tool
	NW_PER_MERCHANTTOOL:"https://personalnatwestcom-nfte1.arete.managedtest.com/personal/merchant.html?dsd",
	NW_PER_MERCHANTTOOL_MOB:"https://personalnatwestcom-nfte1.arete.managedtest.com/personal/merchant.m.html?dsd",


	//Overdraft Calculator

	NW_PER_OVERDRAFT_CAL:'https://personal.natwest.com/personal/current-accounts/overdrafts/olb/overdraft-calculator.html',
	NW_PER_OVERDRAFT_CAL_MOB:'https://personal.natwest.com/personal/current-accounts/overdrafts/olb/overdraft-calculator.m.html'


 };

